tools: s3-tests runner script
aquarist-labs/s3gw-core pull request #205
Opened 2023-01-26 12:02 UTC by m-ildefons

Add an s3tests runner script.

This script wraps around the [s3-tests][1] and manages execution, log and result collection.
The script executes setup and teardown for an s3gw instance for each individual test in order to avoid cascading test failures in case of a crash or corrupted database/file structure. It also collects both the logs from s3gw and from nosetests and compiles a JSON report detailing the individual outcomes of each test.
It will try to automatically determine when to use a runtime container, a full s3gw container or just rely on the host to provide both the binary and the runtime.

It can receive a single test name on the command line or a list of tests in an environment variable to execute.

[1]: https://github.com/ceph/s3-tests.git

Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

Depends on: https://github.com/aquarist-labs/ceph/pull/110

- [x] I have performed a self-review of my code.
- [x] If it is a core feature, I have added thorough tests.
- [x] CHANGELOG.md has been updated should there be relevant changes in this PR.

2023-01-27 17:17 UTC, irq0 requested changes
Quick first pass review

2023-01-27 17:17 UTC, irq0 commented on tests/s3tests-runner.sh
> +CEPH_DIR=${CEPH_DIR:-"/srv/ceph"}
To save some chars one can do:

: "${CEPH_DIR:="srv/ceph"}"

2023-01-27 17:17 UTC, irq0 commented on tests/s3tests-runner.sh
> +#!/bin/bash
There are a couple of quoting in the script. See shellcheck. We probably should add it to pre-commit

2023-01-30 12:16 UTC, m-ildefons commented on tests/s3tests-runner.sh
> +_setup() {
Those are purely to prevent name conflicts with commands on `$PATH` (e.g. `build` I think)

2023-01-30 12:18 UTC, m-ildefons commented on tests/s3tests-runner.sh
> +#!/bin/bash
Hmm... I _am_ running ShellCheck in the editor, so I would have thought it had caught those? Are you running it with a custom config?

2023-01-30 12:23 UTC, m-ildefons commented on tests/s3tests-runner.sh
> +CEPH_DIR=${CEPH_DIR:-"/srv/ceph"}
I didn't know that. Do you think this is more readable? I kind of dislike the heavier use of specifically placed colon `:` characters, which doesn't seem to be very error-tolerant. And if errors happen they seem hard to spot, but this is probably personal preference.

2023-01-30 12:24 UTC, m-ildefons commented on tests/s3tests-runner.sh
> +
Well... Then the tests won't run to the end, but ok

2023-02-09 15:31 UTC, jecluis requested changes
otherwise looks good

2023-02-09 15:31 UTC, jecluis commented on tests/s3tests-runner.sh
> +    while ! curl -s localhost:7480 > /dev/null ; do sleep .1 ; done
can we maybe limit the amount of time we are willing to wait? If by chance the daemon dies (e.g., unforeseen error condition), then we'll be looping forever.

2023-02-09 15:31 UTC, jecluis commented on tests/s3tests-runner.sh
> +  TMPFILE="$(mktemp -q -p "${OUTPUT_DIR}" report.XXXXXX.ymal)"
s/ymal/yaml/

2023-02-09 15:41 UTC, m-ildefons commented
This entire repo is now deprecated. Continue the discussion on the main s3gw repo, e.g. here: https://github.com/aquarist-labs/s3gw/pull/340

2023-02-09 15:41 UTC, closed without merging