s3gw with NGINX ingress by default
aquarist-labs/s3gw-core pull request #57
Opened 2022-05-19 16:01 UTC by giubacc

- Now the environment, K3s and K8s are provisioned by default with NGINX ingress.
- K3s provisioning is now much more consistent with K8s counterpart, the only different playbook is the one installing K3s.

Fixes: https://github.com/aquarist-labs/s3gw-core/issues/45
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

2022-05-19 16:11 UTC, votdev requested changes

2022-05-19 16:11 UTC, votdev commented on env/generate-spec.sh
> +rgw_default_user_access_key_base64=$(cat s3gw/s3gw-secret.yaml | grep RGW_DEFAULT_USER_ACCESS_KEY | cut -d':' -f 2 | sed -e 's/[[:space:],"]//g')
This looks incorrect. The access/secret key is defined as string data in the secret file. The old code is loading the yaml file via `kubectl get` which automatically converts `stringData` (plain text) to `data` (base64 encoded). That's why `jsonpath={.data` is used instead of `jsonpath={.stringData`.

2022-05-20 08:27 UTC, giubacc commented on env/generate-spec.sh
> +rgw_default_user_access_key_base64=$(cat s3gw/s3gw-secret.yaml | grep RGW_DEFAULT_USER_ACCESS_KEY | cut -d':' -f 2 | sed -e 's/[[:space:],"]//g')
I try to install a fresh installation of k3s env but I found that 
`kubectl get -f s3gw/s3gw-secret.yaml -o 'jsonpath={.data.RGW_DEFAULT_USER_ACCESS_KEY}`
is failing with an empty environment.
`-f` option is used by `kubectl` to identify an existing resource inside the cluster.
If that resource does not exist yet, the command fails.
I assumed that the code was intended to extract `RGW_DEFAULT_USER_ACCESS_KEY` directly from the file.
So I write a version that does not rely on kubectl command. 
If I misunderstand the original intent, please explain me what it was.

2022-05-20 09:12 UTC, giubacc commented on env/generate-spec.sh
> +rgw_default_user_access_key_base64=$(cat s3gw/s3gw-secret.yaml | grep RGW_DEFAULT_USER_ACCESS_KEY | cut -d':' -f 2 | sed -e 's/[[:space:],"]//g')
but, you right, the command should return the base64 values for the extracted strings.
so the command should be finally ended with

`| base64`

2022-05-20 13:24 UTC, votdev requested changes

2022-05-20 13:24 UTC, votdev commented on env/s3cmd.cfg
> +add_encoding_exts =
Could you please take care that your IDE removes useless blanks at the end of the line, otherwise each PR will make much noise when your IDE adds the blanks and other IDEs remove it again.
The easiest solution would be to install an [EditorConfig](https://EditorConfig.org) plugin in your IDE; check the [config](https://github.com/aquarist-labs/s3gw-core/blob/main/.editorconfig#L9) we are shipping with this project.

2022-05-20 14:59 UTC, votdev requested changes
I'm not able to run `setup_k3s.sh` successfully. It seems the ingress is not deployed correctly because it does not get any IP address.
```
$ ./setup_k3s.sh --dev
...
service/s3gw-service created
ingress.networking.k8s.io/longhorn-ingress created
secret/lh-secret created
ingress.networking.k8s.io/s3gw-no-tls-ingress created
secret/s3gw-ingress-secret created
ingress.networking.k8s.io/s3gw-ingress created
Waiting for cluster to become ready.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```
```
$ kubectl get -n s3gw-system ingress
NAME           CLASS   HOSTS        ADDRESS   PORTS     AGE
s3gw-ingress   nginx   s3gw.local             80, 443   23m
$ kubectl get -n longhorn-system ingress             
NAME               CLASS   HOSTS            ADDRESS   PORTS     AGE
longhorn-ingress   nginx   longhorn.local             80, 443   30m
```

2022-05-20 15:18 UTC, votdev commented
Rebuilding the yaml file with `./generate-spec.sh --dev --output s3gw-dev.yaml --traefik` successfully installs the cluster.
```
ingress.networking.k8s.io/s3gw-ingress created
Waiting for cluster to become ready................................................................................................................................................................

Longhorn UI available at http://192.168.178.43:80/longhorn/
s3gw available at http://192.168.178.43:80/s3gw/

$ kubectl get -n s3gw-system ingress                   
NAME           CLASS    HOSTS   ADDRESS          PORTS   AGE
s3gw-ingress   <none>   *       192.168.178.43   80      9m5s
```

2022-05-23 07:37 UTC, giubacc commented
> Rebuilding the yaml file with `./generate-spec.sh --dev --output s3gw-dev.yaml --traefik` successfully installs the cluster.
> 
> ```
> ingress.networking.k8s.io/s3gw-ingress created
> Waiting for cluster to become ready................................................................................................................................................................
> 
> Longhorn UI available at http://192.168.178.43:80/longhorn/
> s3gw available at http://192.168.178.43:80/s3gw/
> 
> $ kubectl get -n s3gw-system ingress                   
> NAME           CLASS    HOSTS   ADDRESS          PORTS   AGE
> s3gw-ingress   <none>   *       192.168.178.43   80      9m5s
> ```
> 
> IMO this indicates that the nginx ingress configuration is buggy.

Thanks for your testing; I realized that the installation on the host is flawed, it misses to install the ingress controller.
There is a specific playbook that runs when installing on a vm; that is not called when you install from the host.

2022-05-23 07:40 UTC, giubacc commented on env/generate-spec.sh
> +rgw_default_user_access_key_base64=$(cat s3gw/s3gw-secret.yaml | grep RGW_DEFAULT_USER_ACCESS_KEY | cut -d':' -f 2 | sed -e 's/[[:space:],"]//g')
@votdev can you confirm that 
`kubectl get -f s3gw/s3gw-secret.yaml -o 'jsonpath={.data.RGW_DEFAULT_USER_ACCESS_KEY}`
was intended to extract a base64 value from the file?
Do you agree with the solution not relying on kubectl?

2022-05-23 09:34 UTC, votdev commented on env/generate-spec.sh
> +rgw_default_user_access_key_base64=$(cat s3gw/s3gw-secret.yaml | grep RGW_DEFAULT_USER_ACCESS_KEY | cut -d':' -f 2 | sed -e 's/[[:space:],"]//g')
> @votdev can you confirm that `kubectl get -f s3gw/s3gw-secret.yaml -o 'jsonpath={.data.RGW_DEFAULT_USER_ACCESS_KEY}` was intended to extract a base64 value from the file? 

Yes, the intention was to easily get the base64 string.

> Do you agree with the solution not relying on kubectl?

Yes, please go ahead.

2022-05-24 14:08 UTC, votdev requested changes

2022-05-24 14:08 UTC, votdev commented on env/README.md
> +10.46.201.101   longhorn.local s3gw.local s3gw-no-tls.local
Which IP address is this when using k3s on bare metal?

2022-05-24 14:11 UTC, votdev commented
> @votdev I should have fixed the problem with the installation of K3s on bare metal. Unfortunately on my machine K3s installation on bare metal is someway defective, it seems that all pvc created by LH are unavailable; I still haven't investigated the issue.

Here the PVC is up and running.
```
$ kubectl get pvc -n s3gw-system   
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
s3gw-pvc   Bound    pvc-fe46f9f3-8a2a-4c3a-bf68-2d552d60e94c   2Gi        RWO            longhorn-single   27m
```
The only problem is the ingress.
```
$ kubectl get ingress -n s3gw-system
NAME                  CLASS   HOSTS               ADDRESS   PORTS     AGE
s3gw-no-tls-ingress   nginx   s3gw-no-tls.local             80        28m
s3gw-ingress          nginx   s3gw.local                    80, 443   28m
```
The `Waiting for cluster to become ready` is waiting infinitely.

2022-05-24 14:42 UTC, votdev commented
Is it possible to do not force the user to use specific hostnames like `s3gw-no-tls.local`, `s3gw.local` or `longhorn.local`? One problem is that `.local` is used for Zeroconf/mDNS. I would suggest to use different ports for Longhorn and s3gw.

I now think to know that the RGW signature problem with Traefik arises due the fact that we strip the prefix. I'll try using different ports instead of URL prefixes. I think then the signature problem will fix itself because the client and server host are looking the same.

2022-05-24 14:47 UTC, giubacc commented on env/README.md
> +10.46.201.101   longhorn.local s3gw.local s3gw-no-tls.local
I think putting 127.0.0.1 should be okay

2022-05-24 15:01 UTC, votdev requested changes

2022-05-24 15:01 UTC, votdev commented on env/s3gw.yaml
> +  AWS_ACCESS_KEY_ID: "MDU1NWIzNTY1NGFkMTY1NmQ4MDQK"
There is a bug in the bas64 encoding script. `0555b35654ad1656d804`becomes `MDU1NWIzNTY1NGFkMTY1NmQ4MDQ=` and NOT `MDU1NWIzNTY1NGFkMTY1NmQ4MDQK`. Something happens to the `=` character.

2022-05-25 07:05 UTC, votdev commented
Can you please resolve that error:
```
This branch has conflicts that must be resolved
to resolve conflicts before continuing.
Conflicting files
env/setup_k3s.sh 
```

2022-05-25 08:09 UTC, votdev requested changes

2022-05-25 08:09 UTC, votdev commented on env/.gitignore
> +cors.xml
Could you please move that to the `.gitignore` in the root folder? The file may exists also in the `env` directory.

2022-05-25 08:17 UTC, giubacc commented on env/.gitignore
> +cors.xml
Currently this is matching `cors.xml` inside `env` and subdirs.
Should we match-ignore `cors.xml` on the entire project?

2022-05-25 08:18 UTC, giubacc commented on env/README.md
> +10.46.201.101   longhorn.local s3gw.local s3gw-no-tls.local
updated doc with this hint (127.0.0.1 on bare metal)

2022-05-25 08:19 UTC, votdev commented on env/.gitignore
> +cors.xml
Oh sorry, i missed that it is in the correct folder. All right then.

2022-05-25 09:58 UTC, votdev approved these changes
LGTM (k3s)

2022-05-25 10:00 UTC, merged