UI served with a node:lts-alpine image
aquarist-labs/s3gw-core pull request #60
Opened 2022-05-31 16:16 UTC by giubacc

Please read:  build-ui/README.md

Notes:
The bare metal installation of K3s requires you to **manually** build the `s3explorer` image first.
The virtual machine installation of K3s is completely automated, you only need to run: `./setup_k3s.sh --vm`. 

Currently the s3gw-ui consists of 1 application: `s3explorer`.
This application is being built cloning this code: https://github.com/giubacc/aws-s3-explorer/tree/s3gw-demo
That application was actually working some weeks ago, but now there are issues and probably this isn't working.
The aim of this PR, btw, is to provide a *methodology* to build/run a UI with s3gw environment.  
So, treat the `s3explorer` in this form as a non working application.
What will be the real `s3explorer` could be delivered inside s3gw with the same method proposed with this PR.

Fixes: https://github.com/aquarist-labs/s3gw-core/issues/46
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

2022-06-01 07:50 UTC, votdev requested changes

2022-06-01 07:50 UTC, votdev commented on build-ui/build-ui.sh
> +IMAGE_NAME=${IMAGE_NAME:-"s3explorer"}
Doesn't it make sense to name this `s3gw-ui` and make the name independent from what we deliver with this container? Right now we are using s3explorer for demo purposes., but we will surely change that as soon as we start implementing our own UI. So, using a independent name does not need any additional changes in other scripts after the switch.

2022-06-01 15:15 UTC, votdev commented on build-ui/README.md
> +This documentation will guide you through the several steps to build an
```suggestion
This documentation will guide you through the several steps to build a
```

2022-06-01 15:16 UTC, votdev commented on build-ui/README.md
> +Currently supported `s3gw-UI` images are:
```suggestion
Currently, supported `s3gw-UI` images are:
```

2022-06-01 15:18 UTC, votdev commented on build-ui/README.md
> +* Dockerfile's filename must end with `.{s3gw-UI-image-name}`, eg: *Dockerfile.s3explorer*
```suggestion
* Dockerfile's filename must end with `.{s3gw-UI-image-name}`, e.g.: *Dockerfile.s3explorer*
```

2022-06-01 15:21 UTC, votdev commented on build-ui/README.md
> +You can build an `s3gw-UI` image by running the `build-ui.sh` script.
I'm not absolutely sure here, but i think it is `a` because `s3 gw-UI` stands before `image`.
```suggestion
You can build a `s3gw-UI` image by running the `build-ui.sh` script.  
```

2022-06-01 15:21 UTC, votdev commented on build-ui/README.md
> +You can run an `s3gw-UI` application with:
```suggestion
You can run a `s3gw-UI` application with:
```

2022-06-01 15:23 UTC, votdev commented on build-ui/README.md
> +  http://10.0.2.100:8080
Make this more generic to match the users environment.
```suggestion
  http://<YOUR_HOST_IP>:8080
```

2022-06-03 09:36 UTC, m-ildefons commented on env/playbooks/s3gw-ui-deploy.yaml
> +      command: git clone "{{ s3explorer_repo }}" --branch "{{ s3explorer_branch }}" /home/{{ user }}/s3gw-ui/s3explorer
Why not use [Ansible's git module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html)? Doing it with a `command` has the disadvantage of being very fragile, breaking idempotency and generally working against Ansible's declarative nature.

This basically turns Ansible into a `ssh $HOST < script.sh` command.

2022-06-03 09:36 UTC, m-ildefons commented on env/playbooks/s3gw-ui-deploy.yaml
> +      command: docker save --output /home/{{ user }}/s3gw-ui/s3explorer.tar localhost/s3explorer:latest
Why not use [Ansible's docker_image module](https://docs.ansible.com/ansible/2.6/modules/docker_image_module.html#docker-image-module)? See above.

2022-06-03 09:36 UTC, m-ildefons commented on env/playbooks/s3gw-ui-deploy.yaml
> +      command: "{{ item }}"
Again, there is [an Ansible module](https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html#ansible-collections-kubernetes-core-k8s-module) doing what this command is doing, only in a way that does not negate half of the reasons to use Ansible.

2022-06-06 08:02 UTC, giubacc commented on env/playbooks/s3gw-ui-deploy.yaml
> +      command: git clone "{{ s3explorer_repo }}" --branch "{{ s3explorer_branch }}" /home/{{ user }}/s3gw-ui/s3explorer
That's true, but I think Ansible syntax is much more clear than a simple `sh` script. Even when using it with simple commands.
I appreciate that you can initially approximate something with a raw command and then you can refine it with the more appropriate module.
I will try to patch these suggestions, thank you!

2022-06-06 09:37 UTC, giubacc commented on env/playbooks/s3gw-ui-deploy.yaml
> +      command: "{{ item }}"
see above

2022-06-06 09:40 UTC, giubacc commented on build-ui/build-ui.sh
> +IMAGE_NAME=${IMAGE_NAME:-"s3explorer"}
@m-ildefons @0xavi0 what your opinion regarding having one or more than one image for ui?
What default would you use for IMAGE_NAME?

2022-06-08 08:57 UTC, m-ildefons commented on build-ui/build-ui.sh
> +IMAGE_NAME=${IMAGE_NAME:-"s3explorer"}
As discussed in slack, I don't think we should have more than one image for the UI. Here is my reasoning:

Do we have 'enough' UI applications that this makes sense? Do we gain any significant advantage from it?

There are a couple of worries for me:
1) Do we know that we're able to define stable APIs ahead of time for communication between containers, or will this end up being "Version-Hell 2.0: The return of headaches"
2) This significantly increases complexity for small deployments. The whole premise of the s3gw is to be small and scaled down, I fear we'll not excel if we go down this route
3) At some point this will result in the explorer and the user management UIs using different UI toolkits, meaning that in our team there will be two sub-teams using incompatible technologies, unable to share knowledge.
4) Two+ runtimes running two+ webservers binding two+ ports, requiring two+ routes... that's everything but a minimal footprint

The advantages I can see right of the bat are:
1) Users can customize which UI features they even want to deploy (do they event want that?)
2) We can make changes to individual components and release them individually
3) We'll probably reduce test time, improving the development experience

So all in all I think it's a hack that only serves to re-use the s3explorer while we don't have our own implementation. After that it's likely going to be a straight pain. We want something that is small, simple and hard to break, N containers for the UI is everything but that.
I do think that separating the UI from the actual S3 gateway makes a lot of sense, because this allows our users to run it with or without UI.

2022-06-08 10:16 UTC, giubacc commented on build-ui/build-ui.sh
> +IMAGE_NAME=${IMAGE_NAME:-"s3explorer"}
Thanks @m-ildefons, I tend to agree with you so I'm going to implement the original @votdev change request.

2022-06-08 13:57 UTC, jecluis approved these changes

2022-06-08 13:58 UTC, merged