This PR updates the readme file. Highlights:
aquarist-labs/s3gw-core pull request #74
Opened 2022-06-13 15:57 UTC by jhmarina

* Updated the MVP text & graphic (made it slimmer to make better use of the real estate)
* Added status badges. These are the ones I found currently, we may be able to add more in the future
* Quick start section for Helm chart & Docker container
* Moved the container build information back to the `build/` folder.
* Added the table in the RGW S3 compatibility page. Please let me know if it needs amending.

Fixes: #43

Signed-off-by: Jesus Herman <jherman@suse.com>

2022-06-13 18:08 UTC, jhmarina commented
@jecluis How on Earth did that happen! 😱I'll change it straight away

2022-06-14 07:40 UTC, giubacc commented
There was a specific reason that leaded to put the s3gw container build instructions directly on the main readme?
I'm asking because we currently have more specialized readmes inside some sub-directories.

2022-06-14 08:04 UTC, jecluis commented
@jhmarina I meant the actual commit, not the PR's title ;)

2022-06-14 09:45 UTC, jhmarina commented
@jecluis my bad, I forgot to push the change. Should be ok now!

2022-06-14 09:51 UTC, votdev requested changes

2022-06-14 10:53 UTC, m-ildefons commented on README.md
> +This project will provide the required infrastructure to build a container
'This project provides'

2022-06-14 10:57 UTC, m-ildefons commented on README.md
> +After delivering an initial proof of concept, we're currently focusing on developing a Minimum Viable Product. Once we achieve this deliverable and depending on the user feedback being positive, amon
This is how waterfall-like development usually works. The interesting part of our roadmap is which features are done, which are being worked on and which are planned for the future. Also interesting is what can be expected of the upcoming MVP.

2022-06-14 11:24 UTC, m-ildefons reviewed
Just some really small nits, but I think the readme would improve in readability for 'outsiders' not familiar with the project.
Over all, I cry a little inside whenever I read ceph-specific language like RGW or dbstore in the readme, because I think we should not expect that our users are familiar with ceph.
This is particularly important IMO for the readme, because a new user will see it first. If it's sprinkled with too much specific and niche abbreviations, they might turn away.
Some suggestions:
RGW/radosgw --> Gateway or s3gw
DBStore --> SQLite
I addition to that, there is still quite a bit of technical detail documentaion, like the whole developing section, that I personally would rather move into a docs directory and then reference to it, because the landing page should not burden the reader with this kind of involved information.
My vision for the readme is that there is everything to get started (as a user) right on it:
- description
- quickstart guide
- project roadmap
- report issues / contact
- license
And everything else is just linked:
- Development environment
- Howto build your own containers
- contributing guidelines
- technical documentation / deep explanations

Other than that this is a big improvement over the old readme, especially the new roadmap image is much better.

2022-06-14 12:53 UTC, jecluis requested changes

2022-06-14 12:53 UTC, jecluis commented on README.md
> +We're building an S3-compatible Gateway based on Ceph RGW, using a non-RADOS backend for
While we could argue the "we" is the folks at  aquarist-labs, I agree with @m-ildefons that this seems just a bit of unnecessary fluff. But this is really just a matter of taste IMO.

2022-06-14 12:53 UTC, jecluis commented on README.md
> +This project will provide the required infrastructure to build a container
agreed, the project now provides what is needed.

2022-06-14 12:53 UTC, jecluis commented on README.md
> +After delivering an initial proof of concept, we're currently focusing on developing a Minimum Viable Product. Once we achieve this deliverable and depending on the user feedback being positive, amon
Right, we should focus on saying we'll be releasing intermediate versions towards an MVP, and then describe what an MVP looks like. Although the MVP is the final deliverable, we will have multiple deliverables in between, and adjust/course correct as we go.

2022-06-14 12:53 UTC, jecluis commented on README.md
> +| Storage Class             | ✅       |
While this is true for `radosgw`, it is not true for `s3gw` because our file backend does not yet support the vast majority of these things. I would suggest leaving all of them empty except for those listed below.

* List/Create/Delete buckets
* Put/Delete/Get Object

2022-06-14 15:09 UTC, jhmarina commented on README.md
> +After delivering an initial proof of concept, we're currently focusing on developing a Minimum Viable Product. Once we achieve this deliverable and depending on the user feedback being positive, amon
Usually, the purpose of an MVP is to gather customer/stakeholder data as soon as possible and then iterate or pivot. On waterfall development, all requirements are defined and then the work is executed, without gathering feedback incrementally, which I don't think is what the text says, but clearly I'm not getting the right message across.  Let me rewrite it 👍

2022-06-16 11:37 UTC, jhmarina commented on README.md
> +After delivering an initial proof of concept, we're currently focusing on developing a Minimum Viable Product. Once we achieve this deliverable and depending on the user feedback being positive, amon
@m-ildefons @jecluis I've streamlined the text a bit and added a list of features we've worked on. Both the text & the graphic may change, depending on our progress & what we discuss next Friday.  But I've tried to improve the MVP description a bit. Please let me know your thoughts

2022-06-16 11:37 UTC, jhmarina commented on README.md
> +For more information on building and running a container, please read our [guide](./build/) on building and running
Updated @votdev

2022-06-17 08:44 UTC, jecluis requested changes
@jhmarina I'm not a fan of merge commits on branches this size, as I think it ends up polluting the history unnecessarily on merge. If you wouldn't mind, I'd prefer if you were to cherry-pick your patches on top of an up-to-date branch, and force push the changes out.

Additionally, it might make sense to squash some of those commits together.

And aside from dropping the `podman` mention in the README, I think this is okay to merge once the above is addressed.

2022-06-17 08:44 UTC, jecluis commented on README.md
> +docker run -p 7480:7480 localhost/s3gw
I have qualms with this change. IMO it should state something like "use docker if you have it, or podman instead". I doubt most of us are testing using docker..

2022-06-17 11:29 UTC, jhmarina commented on README.md
> +docker run -p 7480:7480 localhost/s3gw
You're looking at the "Quickstart" section. The build & run instructions have been moved to a section of their own (.docs/build.md), but I'll add the podman command here too if it's needed.

2022-06-17 11:46 UTC, jecluis commented on README.md
> +docker run -p 7480:7480 localhost/s3gw
I understand that, but I think it's worthwhile mentioning podman here as well. I would go as far as stating that's the preferred method, unless there's a reason to prefer docker over podman.

2022-06-17 13:35 UTC, closed without merging