RFC: Use MADRs to records architecture, design and code decisions
aquarist-labs/s3gw-core pull request #98
Opened 2022-07-19 10:59 UTC by irq0

Uses template from https://adr.github.io/madr/

2022-07-19 11:13 UTC, jhmarina commented
The linter is finding issues with other md files. I'm going to create an issue to sort them out separately.

I like the idea of using MADRs for architecture design & code. Other devs should have a look to, but it lgtm

2022-07-19 14:49 UTC, giubacc commented
I think this process can be good in many ways, btw, I would like to highlight some thoughts:

1. what is a "decision" ? should we define what we intend with that? I constantly make decisions when developing/writing/designing, but I don't think every decision is worth to be reported to the entire team.
So if we give an approximation of what we are thinking when are we talking about a decision, that would be good, IMO.

2. everything that falls into "decision" category must therefore follow this process, is there a risk to add overhead?
3. could this process be addressed with regular meetings?
4. PR/issues aren't already defining a decision/feedback making process?

2022-07-20 12:59 UTC, jhmarina commented
Currently, we have different approaches to discussing topics & coming up with decisions. We have Slack, calls & email. I try to get information from all mediums and summarize & document everything as good as I can. Which doesn't always work.

I think this approach could be seen as a voting mechanism. We discuss topics on different mediums but we resort to using ADR to reach a consensus.

I would like to give this approach a try and figure out if it works as a means of centralizing our decisions. We can try it for a few months and see how it goes.

Now, before going for it, it'd be nice to get feedback from other peers. @0xavi0, @jecluis, @m-ildefons, @votdev do you want to give it a try?

2022-07-21 11:42 UTC, m-ildefons approved these changes
I think this approach has a lot of benefits for an open source project.
The crux is and will always be that someone needs to take discussions that happened elsewhere (slack, emails, etc) and summarize them, but this would apply to other solutions like confluence as well, so I don't see that as a problem specific to this approach.
It's certainly a lot better than our current approach with slack. I quite like it.

2022-07-22 06:37 UTC, jecluis reviewed
lgtm

2022-07-22 06:38 UTC, jecluis commented
Also, this will require a following PR to fix all the linting issues across the repo.

2022-07-22 07:28 UTC, jecluis approved these changes

2022-07-22 12:16 UTC, irq0 commented
> Also, this will require a following PR to fix all the linting issues across the repo.

@m-ildefons fixed the .md linter errors, thanks!

2022-07-22 13:31 UTC, jecluis requested changes

2022-07-22 13:31 UTC, jecluis commented on README.md
> +i### Docker
this feels like a typo? That `i` in the beginning?

2022-07-22 13:32 UTC, jecluis commented on README.md
> +i### Docker
It also breaks rendering the header.

2022-07-22 13:48 UTC, irq0 commented on README.md
> +i### Docker
```suggestion
### Docker
```

2022-07-22 13:51 UTC, irq0 commented on README.md
> +i### Docker
Done

2022-07-22 14:05 UTC, jecluis approved these changes

2022-07-22 14:06 UTC, merged